### ISSUE TITLE
Multiple accordions on same page

### ISSUE THREAD

**Issue by intelligence** [18F/accordion#10]
Having issues getting this to work with multiple accordions on the same page. I'm setting body, but it still initializes on my first accordion (ul.accordion.js-accordion), the default one.

An example would be cool.

**Comment by noahmanger** [comment]
Ah yes. You'll need to set a unique `contentPrefix` in the `options` object when each accordion is initialized. Something like: 

```
new accordion.Accordion(selectors, { 
  contentPrefix: 'accordion-1'
});
```

Because the library programmatically associates each content div with a button, it uses the `contentPrefix` as prefix for these IDs.

Let me know if that doesn't work!

**Comment by intelligence** [comment]
Thanks for such a quick reply!

I actually tried that too, but maybe I'm screwing it up some other way. 
Here's what I tried:

```
const accordion = require('aria-accordion');
const selectors = document.querySelectorAll('.js-accordion');
for (let i = 0, len = selectors.length; i < len; i += 1) {
  const selector = selectors[i];
  const thing = new accordion.Accordion(selector, {
    collapseOthers: true,
    openFirst: true,
    contentPrefix: `accordion${i}`,
  });
}
```

**Comment by intelligence** [comment]
Hey Noah. Sorry to hassle, but did you have a look at this? I cannot understand what's causing it not to work. Might be a misunderstanding from my part. Did you try the code I posted above?

**Comment by noahmanger** [comment]
Sorry for the delay. I haven't been able to test it out. The `contentPrefix` part looks correct, but it looks like the `selector` param isn't what's expected. The first param of `Accordion` should be an object like: 

```
{
  body: '.js-accordion',
}
```

Rather than passing in one of the results of your `selectors` query.

I see how that might be a little counterintuitive and maybe the README should be updated. Let me know if that doesn't work.

**Comment by noahmanger** [comment]
Just checking in on this. @intelligence were you able to resolve your issue?

**Comment by intelligence** [comment]
Sorry @noahmanger I went with another solution in the end as I could not get it to work.

**Comment by noahmanger** [comment]
All good. Sorry it didn't work!
